name: Package Addon

on:
  push:
    branches: [main]
    tags: ["*"]

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Clone project
        uses: actions/checkout@v3

      - name: Package and release for Classic Era
        uses: BigWigsMods/packager@v2
        with:
          args: -g classic -S

      - name: Package and release for Wrath of the Lich King Classic
        uses: BigWigsMods/packager@v2
        with:
          args: -g wrath -S
